package com.appsinventiv.noorenikah.callWebRtc.callBroadCast;

/**
 * Created by JunaidAy on 23/01/2018.
 */

public enum CallEndType {
    CALLER_ENDED_INDIVIDUAL_CALL,
    CALLER_ENDED_INDIVIDUAL_VIDEO_CALL,
    END_INDIVIDUAL_CALL,
    END_INDIVIDUAL_VIDEO_CALL,
    INDIVIDUAL_MISSED_CALL,
    INDIVIDUAL_MISSED_VIDEO_CALL,
    RECEIVER_REJECT_INCOMIING_CALL,
    RECEIVER_REJECT_INCOMIING_VIDEO_CALL,
    RECEIVER_ACCEPT_INCOMING_CALL,
    RECEIVER_ACCEPT_INCOMING_VIDEO_CALL,
    CALLER_ENDED_GROUP_CALL,
    END_GROUP_CALL,
    RECIEVER_REJECT_GROUP_CALL,
    RECIEVER_ACCEPT_GROUP_CALL,
    GROUP_MISS_CALL,
}
