package com.appsinventiv.noorenikah.callWebRtc.callBroadCast;

/**
 * Created by JunaidAy on 12/11/2017.
 */

public enum EventsFromActivity {
    END_CALL_PRESSED,
    END_CALL_INGOING,
    END_CALL_INCOMING,
    MUTE_BUTTON_PRESSED,
    UNMUTE_BUTTON_PRESSD,
    ENABLE_LOUD_SPEAKER_PRESSED,
    DISABLE_LOUD_SPEAKER_PRESSED,
    ACCEPT_CALL_PRESSED,
    REJECT_CALL_PRESSED,
    GET_LATEST_TIME,
    GET_UPDATED_PARTICIPANTS,
    HOLD_BUTTON_PRESSED,
    UNHOLD_BUTTON_PRESSED,
    DISCONNECT_USER,
    REDIAL_USER,
    START_CALLING_ACTIVITY,
    ADD_PERSON_TO_CALL,
    REMOVE_USER_FROM_CALL_LIST,
    IS_POP_INFALTED,
    POP_UP_INFLATED,
    UPDATE_SCHEDULE_END,
    LOCAL_RENDER_VIEW,
    ENABLE_VIDEO,
    DISABLE_VIDEO,
    SHOW_REMOTE_VIEW

}
